// Payload shapes carried across the main↔renderer boundary. Reuse the format types so there is
// one definition of a node; the renderer reads these, never the raw .alethic files.
import type { IndexJson, NodeMeta } from '@alethic/format';

/** One parsed node as shipped to the renderer (meta null only when conflict markers corrupt it). */
export interface SnapshotNode {
  path: string;
  meta: NodeMeta | null;
  body: string;
  conflict: boolean;
}

/** A whole-project snapshot: the derived index plus every node's content. */
export interface AtlasSnapshot {
  root: string;
  index: IndexJson;
  nodes: SnapshotNode[];
  mode: 'dev' | 'plan'; // dual-mode (decision 54): code project vs general-planning project
}

/** A live patch pushed when one `.alethic/` file changes on disk (decision 12). */
export interface AtlasEvent {
  reason: 'add' | 'change' | 'unlink';
  path: string; // posix, relative to the .alethic dir
  index: IndexJson; // fresh index after the change
  node?: SnapshotNode; // the new node content (absent on unlink)
}

/** A recently opened project, remembered across sessions (decision 37). */
export interface RecentProject {
  path: string;
  name: string;
  lastOpened: string; // ISO-8601
}

/** An action dispatched from the native application menu to the renderer (decision 37). */
export interface AppMenuEvent {
  action: 'open-folder' | 'open-recent' | 'close-project';
  path?: string; // set for 'open-recent'
}

/** A source file's content, read on demand for the code viewer (decision 47). */
export interface CodeFile {
  path: string; // repo-relative path (as stored on the anchor)
  text: string;
}

/** A file the user attached to a chat message via the composer's "+" — picked and read in main. */
export interface AttachedFile {
  path: string; // absolute path the user chose
  name: string; // basename, shown as a chip
  text: string; // file contents (capped), folded into the message context on send
}

// ── agent / auth / chat (Phase 4) ──────────────────────────────────────────

/** Claude connection state (implementation-plan §2.1, decision 38). */
export interface AuthStatus {
  connected: boolean;
  method: 'oauth' | 'apikey' | null;
  email?: string; // present when signed in via the Claude Code CLI (OAuth)
  plan?: string; // e.g. "pro" / "max" — from `claude auth status`
  cliAvailable?: boolean; // whether the `claude` CLI is on PATH (drives the Connect-with-Claude-Code button)
}

/** A selectable model (decision 8). */
export interface ModelOption {
  id: string;
  label: string;
}

/** One finished step of an assistant turn, persisted so the chain survives (decision 23). Tools are
 * always resolved here (done/error) — a persisted turn has no in-flight steps. */
export type ChatStep =
  | { kind: 'text'; text: string }
  | { kind: 'tool'; name: string; input: unknown; status: 'done' | 'error' };

/** One line of chat history, persisted per-project (decision 23). */
export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant' | 'tool' | 'system';
  text: string;
  ts: string; // ISO-8601
  // Assistant turns keep their full tool/text chain so history renders like the live transcript.
  steps?: ChatStep[];
}

/** A normalized streamed agent event (mirrors packages/agent's AgentEvent, kept dependency-free here). */
export type AgentEventLite =
  | { type: 'started' } // emitted the moment a task begins, so the UI shows "working" immediately
  | { type: 'text'; text: string }
  | { type: 'tool'; name: string; input: unknown }
  | { type: 'tool-result'; name?: string; isError?: boolean }
  | { type: 'usage'; outputTokens: number } // tokens generated by the current step, for the pill
  | { type: 'done'; ok: boolean }
  | { type: 'error'; message: string };

/** An agent event tagged with its task. */
export type AgentStreamMessage = { taskId: string } & AgentEventLite;

/** A permission prompt raised by the agent, awaiting the user's decision (like Claude Code). */
export interface PermissionRequest {
  requestId: string;
  taskId: string;
  toolName: string;
  input: unknown;
}

/**
 * What the agent may currently do without asking (decision 1): the tools blanket-approved with
 * "Allow this session", and whether auto-accept-edits is on. `editTools` is what that mode covers,
 * so the UI names them instead of hard-coding a list of its own.
 */
export interface SessionGrants {
  tools: string[];
  autoAcceptEdits: boolean;
  editTools: string[];
}

/** A recorded agent run (JSONL log, decision 13). */
export interface RunLogEntry {
  file: string;
  taskId: string;
  role: string;
  model: string;
  startedAt: string;
}

/** The raw content of one run log, for the JSONL viewer (decision 13). */
export interface RunLogContent {
  file: string;
  text: string;
}

/** The result of the static update check (decision 33). `available` drives the banner. */
export interface UpdateInfo {
  current: string;
  latest: string;
  available: boolean;
  url?: string;
  notes?: string;
}

// ── scan flow (Phase 6) ────────────────────────────────────────────────────

/** A domain the user confirms before scanning (decision 6). */
export interface DomainProposal {
  slug: string;
  title: string;
  // `| undefined` so zod-inferred payloads (which carry explicit undefined) assign under
  // exactOptionalPropertyTypes.
  description?: string | undefined;
  scope: string[];
}

/** What a scan will cost, shown before it starts (decision 39). */
export interface ScanPreview {
  root: string;
  files: number;
  domains: DomainProposal[];
  estimatedCalls: number;
  large: boolean; // over the size guard → deep scans must be chosen, rest go shallow (decision 7)
  threshold: number;
}

/** Live scan progress — drives the growing pyramid and the ticking counter. */
export interface ScanProgress {
  phase: 'repo-map' | 'decompose' | 'scanning' | 'done' | 'cancelled' | 'error';
  domain?: string;
  completed: number;
  total: number;
  message?: string;
}

/**
 * Whether a scan pass is in flight. Asked on mount by the surfaces that must not offer a second
 * one while it runs (the node card's Deepen/Rescan, the chat composer) — progress events carry
 * them from there.
 */
export interface ScanActivity {
  running: boolean;
  domain?: string;
}

/** The post-scan calibration prompt: the three most central rules, "check me" (decision 40). */
export interface CalibrationRule {
  id: string;
  title: string;
  path: string;
}

// ── liveness: stale → drift → resolution (Phase 7) ─────────────────────────

/** Live progress of a sync pass — detection then per-rule auto-verdicts (decision 18). */
export interface SyncProgress {
  phase: 'checking' | 'judging' | 'done' | 'error';
  rule?: string; // title of the rule being judged
  completed: number;
  total: number;
  message?: string;
}

/** The outcome of a sync pass, shown as a passive banner (decision 15). */
export interface SyncResult {
  ran: boolean;
  method: 'git' | 'mtime' | 'none';
  changedFiles: number;
  staleCount: number; // rules moved to stale this pass
  annotationsChanged: number;
  rescanDomains: string[]; // domains past the 30% degradation threshold (§5.5)
  /**
   * One line per newly-stale feature, naming the *place inside it* that moved — "Adding a task —
   * changed: cmd_add (## Invariants) · 3 other anchors unchanged" (format-spec §5.3). A feature
   * carries many anchors, so "3 newly stale" alone tells the reader nothing about what to look at;
   * this is the deterministic half of the verdict, available before the judge has said a word.
   */
  staleAt: string[];
}

/** The result of a human node edit; `conflict` means the file changed on disk (decision 17). */
export interface SaveNodeResult {
  ok: boolean;
  conflict?: boolean;
  updated: string; // the file's current `updated` timestamp
  title: string; // the current on-disk title (for the reload branch)
  body: string; // the current on-disk body (for the reload branch)
}

// ── planning & execution (Phase 9) ─────────────────────────────────────────

/**
 * Live progress of one plan phase's execution (dev-planning v2, decision 55): it runs, then the
 * scanner maps the code it wrote into the Code branch (`mapping`), then it is `done` — or it never
 * finished (`blocked`). Decision 55 replaced the per-step pipeline of decisions 25/27/42, so there
 * is no promotion or output-guardrail stage any more.
 */
export interface PlanProgress {
  phase: 'executing' | 'mapping' | 'blocked' | 'done' | 'error';
  phaseIndex?: number; // which roadmap phase this progress is about
  phaseTitle?: string;
  message?: string;
}

// ── environment: terminal, processes, git panel (Phase 10) ──────────────────

/** A terminal tab (decision 45). The read-only `executor` kind streams the agent's bash output. */
export interface TerminalSessionInfo {
  id: string;
  title: string;
  cwd: string;
  kind: 'shell' | 'executor';
  pid: number;
  alive: boolean;
}

/** A live, killable process shown in the process manager + status bar (decision 46). */
export interface ProcessInfo {
  id: string;
  title: string;
  cwd: string;
  pid: number;
}

/** Working-tree state for the left Git panel. */
export interface GitStatus {
  branch: string;
  ahead: number;
  behind: number;
  staged: string[];
  unstaged: string[];
  untracked: string[];
  clean: boolean;
}

export interface GitFileDiff {
  file: string;
  patch: string;
}

/** A chunk of terminal output pushed to the renderer (event payload). */
export interface TerminalData {
  id: string;
  data: string;
}
export interface TerminalExit {
  id: string;
  code: number;
}

// ── window chrome ───────────────────────────────────────────────────────────

/**
 * The state the custom title bar renders from. The app is frameless on Windows/Linux (it draws its
 * own controls) and uses the native traffic lights on macOS, so the renderer needs to know which.
 */
export interface WindowState {
  maximized: boolean;
  /** true when the renderer must draw minimize/maximize/close itself (non-macOS). */
  customControls: boolean;
}
