// The agent engine: a thin port over the Claude Agent SDK's query(). Kept behind an interface so
// the AgentService and tests depend on the port, not the SDK subprocess. The real engine wires the
// role system prompt, the alethic MCP tools, the permission callback and model selection.
import { join } from 'node:path';
import {
  query,
  type CanUseTool,
  type Options,
  type SDKMessage,
} from '@anthropic-ai/claude-agent-sdk';

/** Re-exported so the main process can type its permission proxy without importing the SDK. */
export type { CanUseTool } from '@anthropic-ai/claude-agent-sdk';
import { buildPrompt } from './prompts.js';
import { createAlethicMcpServer } from './mcp.js';
import {
  ROLE_TOOLS,
  sdkToolName,
  roleEditsCode,
  MCP_SERVER_NAME,
  type AgentRole,
} from './roles.js';
import { SpecStore } from './spec-store.js';

/** A normalized event surfaced to the app, decoupled from the SDK's large message union. */
export type AgentEvent =
  | { type: 'text'; text: string }
  | { type: 'tool'; name: string; input: unknown }
  | { type: 'tool-result'; name?: string; isError?: boolean }
  | { type: 'usage'; outputTokens: number } // tokens generated by the current step, for the pill
  | { type: 'done'; ok: boolean }
  | { type: 'error'; message: string };

export interface AgentTask {
  role: AgentRole;
  model: string;
  prompt: string;
  cwd: string; // project root (contains .alethic/)
  language?: string;
  depth?: 'full' | 'shallow'; // scanner depth (decision 39)
  abortController?: AbortController;
  canUseTool?: CanUseTool;
}

export interface AgentEngine {
  run(task: AgentTask): AsyncIterable<AgentEvent>;
}

// Every role may read the code; only the Executor may write it / run commands. ToolSearch is how
// the agent discovers the alethic MCP tools it is told to call — without it a role can be handed
// tools it cannot find (seen in the Phase 2 dog-food runs), so every role keeps it.
const READ_TOOLS = ['Read', 'Glob', 'Grep', 'ToolSearch'];
/** Tools that change files. Named separately because auto-accept-edits (decision 1) covers exactly
 * these — running a command is not an edit and keeps asking. */
export const EDIT_TOOLS = ['Write', 'Edit'];
const WRITE_TOOLS = [...EDIT_TOOLS, 'Bash'];

/** What a role may use at all, and what it may use without asking the user. */
export interface ToolPolicy {
  /** The SDK's `tools`: the base set of built-in tools this role can call. The real sandbox. */
  available: string[];
  /** The SDK's `allowedTools`: what runs unattended. Everything else goes through canUseTool. */
  autoApproved: string[];
}

/**
 * The two SDK lists mean different things, and conflating them cost us decision 1 (permission on
 * every file edit / command, like Claude Code) — found by dog-fooding in Phase 2. `allowedTools`
 * does NOT restrict what a role can reach: a bare name there *auto-approves* the tool before
 * canUseTool is consulted, so listing Write/Edit/Bash made the permission prompt unreachable while
 * leaving every other built-in tool available anyway. Availability belongs in `tools`.
 *
 * So: the role's own alethic tools and the read tools run unattended (a scan writes hundreds of
 * schema-validated rules — prompting per rule is unusable), and writing code or running a command
 * always reaches the user.
 */
export function toolPolicy(role: AgentRole): ToolPolicy {
  const editsCode = roleEditsCode(role);
  return {
    available: [...READ_TOOLS, ...(editsCode ? WRITE_TOOLS : [])],
    autoApproved: [...ROLE_TOOLS[role].map(sdkToolName), ...READ_TOOLS],
  };
}

interface ContentBlock {
  type: string;
  text?: string;
  name?: string;
  input?: unknown;
  is_error?: boolean;
}

interface UsageLike {
  input_tokens?: number;
  output_tokens?: number;
  cache_creation_input_tokens?: number;
  cache_read_input_tokens?: number;
}

/** Tokens the model generated for this step — the live "current action" cost, not the running total
 * (input + cache would balloon into tens of thousands and read as the whole conversation). */
function outputTokens(usage: UsageLike | undefined): number {
  return usage?.output_tokens ?? 0;
}

/** The real engine, backed by the Claude Agent SDK subprocess (Claude Code OAuth or API key). */
export class SdkAgentEngine implements AgentEngine {
  async *run(task: AgentTask): AsyncIterable<AgentEvent> {
    const store = new SpecStore(join(task.cwd, '.alethic'));
    const policy = toolPolicy(task.role);

    const options: Options = {
      model: task.model,
      tools: policy.available,
      allowedTools: policy.autoApproved,
      systemPrompt: buildPrompt(task.role, {
        ...(task.language ? { language: task.language } : {}),
        ...(task.depth ? { depth: task.depth } : {}),
      }),
      mcpServers: { [MCP_SERVER_NAME]: createAlethicMcpServer(store) },
      cwd: task.cwd,
      permissionMode: 'default',
      includePartialMessages: true, // stream deltas so the token counter grows live, not in jumps
      ...(task.abortController ? { abortController: task.abortController } : {}),
      ...(task.canUseTool ? { canUseTool: task.canUseTool } : {}),
    };

    // The live output-token counter for the step in flight. Reset at each message boundary so the
    // pill shows the current action's cost; corrected to the API's exact count when it reports one.
    let liveTokens = 0;
    let lastEmitted = 0;

    try {
      for await (const message of query({
        prompt: task.prompt,
        options,
      }) as AsyncIterable<SDKMessage>) {
        if (message.type === 'stream_event') {
          const ev = (message as { event?: StreamEventLike }).event;
          if (!ev) continue;
          if (ev.type === 'message_start') {
            liveTokens = ev.message?.usage?.output_tokens ?? 0;
            lastEmitted = liveTokens;
            yield { type: 'usage', outputTokens: liveTokens };
          } else if (ev.type === 'content_block_delta') {
            const chunk = ev.delta?.text ?? ev.delta?.thinking ?? ev.delta?.partial_json ?? '';
            if (chunk) {
              liveTokens += estimateTokens(chunk);
              if (liveTokens - lastEmitted >= 4) {
                lastEmitted = liveTokens;
                yield { type: 'usage', outputTokens: liveTokens };
              }
            }
          } else if (ev.type === 'message_delta' && ev.usage?.output_tokens) {
            liveTokens = ev.usage.output_tokens; // authoritative running count for this message
            lastEmitted = liveTokens;
            yield { type: 'usage', outputTokens: liveTokens };
          }
          continue;
        }
        yield* mapMessage(message);
      }
    } catch (err) {
      yield { type: 'error', message: err instanceof Error ? err.message : String(err) };
    }
  }
}

/** The slice of a raw streaming event we read for the live token counter. */
interface StreamEventLike {
  type: string;
  message?: { usage?: { output_tokens?: number } };
  delta?: { text?: string; thinking?: string; partial_json?: string };
  usage?: { output_tokens?: number };
}

/** Rough token estimate for a streamed text/json chunk (~4 chars per token) — good enough for a
 * live counter; the exact count lands via message_delta / the completed message. */
function estimateTokens(chunk: string): number {
  return Math.max(1, Math.round(chunk.length / 4));
}

function* mapMessage(message: SDKMessage): Generator<AgentEvent> {
  switch (message.type) {
    case 'assistant': {
      const blocks = (message.message.content ?? []) as ContentBlock[];
      for (const block of blocks) {
        if (block.type === 'text' && block.text) yield { type: 'text', text: block.text };
        else if (block.type === 'tool_use' && block.name)
          yield { type: 'tool', name: block.name, input: block.input };
      }
      const tokens = outputTokens(message.message.usage as UsageLike | undefined);
      if (tokens > 0) yield { type: 'usage', outputTokens: tokens };
      return;
    }
    case 'user': {
      const blocks = (message.message.content ?? []) as ContentBlock[];
      for (const block of blocks) {
        if (block.type === 'tool_result') {
          yield {
            type: 'tool-result',
            ...(block.is_error !== undefined ? { isError: block.is_error } : {}),
          };
        }
      }
      return;
    }
    case 'result': {
      // No usage here — the result's usage is the whole-turn total; the pill tracks the live step.
      yield { type: 'done', ok: message.subtype === 'success' };
      return;
    }
    default:
      return;
  }
}
