// entities/node — the single place the renderer names domain types. Types come from
// @alethic/format (type-only, erased at build) so the schema is never duplicated (plan §8 rule 5);
// snapshot/transport shapes come from @alethic/ipc.
export type {
  NodeMeta,
  RuleMeta,
  DomainMeta,
  SubMeta,
  PlanMeta,
  PlanStepMeta,
  Anchor,
  Status,
  Kind,
  IndexJson,
  IndexNode,
  Rollup,
} from '@alethic/format';
export type {
  AtlasSnapshot,
  SnapshotNode,
  AtlasEvent,
  AppMenuEvent,
  RecentProject,
  CodeFile,
  AuthStatus,
  ModelOption,
  ChatMessage,
  ChatStep,
  AttachedFile,
  AgentStreamMessage,
  PermissionRequest,
  SessionGrants,
  RunLogEntry,
  RunLogContent,
  UpdateInfo,
  DomainProposal,
  ScanPreview,
  ScanProgress,
  ScanActivity,
  CalibrationRule,
  SyncProgress,
  SyncResult,
  SaveNodeResult,
  PlanProgress,
  TerminalSessionInfo,
  TerminalData,
  TerminalExit,
  ProcessInfo,
  GitStatus,
  GitFileDiff,
  WindowState,
} from '@alethic/ipc';
